
server:
  port: 8080

spring:
  application:
    name: codeforge-backend
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/codeforge}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:}

codeforge:
  mongo:
    enabled: ${CODEFORGE_MONGO_ENABLED:true}
  kafka:
    enabled: ${CODEFORGE_KAFKA_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: "%msg%n" # overridden by logstash encoder in logback-spring.xml
