
name: Terraform - AWS

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (plan/apply/destroy)'
        required: true
        type: choice
        options: [plan, apply, destroy]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan/Apply/Destroy
        working-directory: terraform
        env:
          TF_VAR_public_key_path: ${{ secrets.PUBLIC_KEY_PATH }}
          TF_VAR_enable_backend_https: "false"
          TF_VAR_acm_certificate_arn: ""
        run: |
          if [ "${{ github.event.inputs.action }}" = "plan" ]; then
            terraform plan -out=plan.out
          elif [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform apply -auto-approve
          else
            terraform destroy -auto-approve
          fi
